{
 "title": "Membrane Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pipeline elements",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 37, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "content": "graph TD",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Input buffer size inside store/3",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  path,\n  value AS \"value\"\nFROM measurements m JOIN element_paths ep on m.element_path_id = ep.id\nWHERE\n  $__timeFilter(\"time\") and method = 'store'\nGROUP BY 1, path, value\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Input buffer size inside take_and_demand/4",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  path,\n  value AS \"value\"\nFROM measurements m JOIN element_paths ep on m.element_path_id = ep.id\nWHERE\n  $__timeFilter(\"time\") and method = 'take_and_demand'\nGROUP BY 1, path, value\nORDER BY 1"
    }
   ]
  }
 ]
}